image: jekyll/builder:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

stages:
  - build
  - deploy-pages
  - deploy

before_script:
  - bundle install

build:
  stage: build
  script:
    - bundle exec jekyll build -d public
  only:
    - master

pages:
  stage: deploy-pages
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "${SSH_PRIVATE_KEY}" > id_rsa
    - chmod 700 id_rsa
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - rsync -hrvz --delete --exclude=_ -e 'ssh -i id_rsa' public/ www@${HOST_IP}:/var/www/chmartinez.io/html/
  only:
    - master
